import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/home1439768">Home1439768</Link>
        </li>
        <li>
          <Link to="/aboutus1439768">AboutUs1439768</Link>
        </li>
        <li>
          <Link to="/blog1439768">Blog1439768</Link>
        </li>
        <li>
          <Link to="/whycs1439768">WhyCS1439768</Link>
        </li>
        <li>
          <Link to="/solutions1439768">Solutions1439768</Link>
        </li>
        <li>
          <Link to="/whatourclientssay">Whatourclientssay</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
